/**
 * HMAC parity test — verifies `src/transport/hmac.ts` produces byte-for-byte
 * identical output to the canonical HMAC v4 algorithm.
 *
 * Test vectors at `test-vectors/hmac.json` are generated by
 * `scripts/generate-test-vectors.mjs` (which inlines the canonical algorithm
 * verbatim from `_shared/hmac.ts` v4). The SDK port at `src/transport/hmac.ts`
 * is an independent implementation using a manual base64 encoder. The test
 * proves both implementations agree.
 *
 * The same fixtures are also consumed (separately) by a Deno parity script in
 * the docs repo at `docs/agent-tools/test-hmac-parity.ts`, which runs the
 * deployed `_shared/hmac.ts` v4 against them. If both sides match the same
 * vectors, both sides match each other.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  computeBodyHash,
  canonicalizeQuery,
  signCanonical,
  signRequest,
  canonicalPathForSlug,
  toBase64Url,
} from '../src/transport/hmac.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const VECTORS_PATH = resolve(__dirname, '..', 'test-vectors', 'hmac.json');

interface Fixture {
  name: string;
  description: string;
  apiKey: string;
  hmacSecret: string;
  timestamp: number;
  method: 'POST' | 'GET';
  slug: string;
  query: Record<string, string>;
  body: Record<string, unknown>;
  canonicalPath: string;
  canonicalQuery: string;
  expectedBodyHash: string;
  expectedCanonical: string;
  expectedSignature: string;
}

interface VectorsFile {
  description: string;
  fixtureCount: number;
  fixtures: Fixture[];
}

function loadVectors(): VectorsFile {
  const raw = readFileSync(VECTORS_PATH, 'utf8');
  return JSON.parse(raw) as VectorsFile;
}

const vectors = loadVectors();

describe('HMAC parity: test vectors load', () => {
  it('loads the vectors file successfully', () => {
    expect(vectors.fixtures.length).toBeGreaterThanOrEqual(8);
    expect(vectors.fixtureCount).toBe(vectors.fixtures.length);
  });
});

describe('canonicalPathForSlug', () => {
  it('prepends /functions/v1 for plain slug', () => {
    expect(canonicalPathForSlug('get-categories')).toBe('/functions/v1/get-categories');
  });

  it('handles slug with leading slash idempotently', () => {
    expect(canonicalPathForSlug('/get-categories')).toBe('/functions/v1/get-categories');
  });

  it('matches every fixture canonicalPath', () => {
    for (const f of vectors.fixtures) {
      expect(canonicalPathForSlug(f.slug)).toBe(f.canonicalPath);
    }
  });
});

describe('canonicalizeQuery', () => {
  it('returns empty string for empty params', () => {
    expect(canonicalizeQuery(new URLSearchParams())).toBe('');
  });

  it('sorts params alphabetically by key', () => {
    const params = new URLSearchParams({ z_last: 'z', a_first: 'a', m_middle: 'm' });
    expect(canonicalizeQuery(params)).toBe('a_first=a&m_middle=m&z_last=z');
  });

  it('matches every fixture canonicalQuery', () => {
    for (const f of vectors.fixtures) {
      const params = new URLSearchParams(f.query);
      expect(canonicalizeQuery(params)).toBe(f.canonicalQuery);
    }
  });
});

describe('toBase64Url', () => {
  it('replaces + with -, / with _, strips trailing =', () => {
    expect(toBase64Url('AB+/CD==')).toBe('AB-_CD');
    expect(toBase64Url('abc=')).toBe('abc');
    expect(toBase64Url('abcd')).toBe('abcd');
  });
});

describe('computeBodyHash — fixture parity', () => {
  for (const f of vectors.fixtures) {
    it(`[${f.name}] hex SHA-256 matches expected`, async () => {
      const hash = await computeBodyHash(f.body);
      expect(hash).toBe(f.expectedBodyHash);
    });
  }
});

describe('signCanonical — fixture parity', () => {
  for (const f of vectors.fixtures) {
    it(`[${f.name}] HMAC-SHA256 base64url matches expected`, async () => {
      const sig = await signCanonical(f.expectedCanonical, f.hmacSecret);
      expect(sig).toBe(f.expectedSignature);
    });
  }
});

describe('signRequest — full fixture parity', () => {
  for (const f of vectors.fixtures) {
    it(`[${f.name}] produces matching timestamp, signature, bodyHash, canonical`, async () => {
      const result = await signRequest({
        apiKey: f.apiKey,
        hmacSecret: f.hmacSecret,
        method: f.method,
        path: f.canonicalPath,
        query: f.canonicalQuery,
        body: f.body,
        timestamp: f.timestamp,
      });

      expect(result.timestamp).toBe(String(f.timestamp));
      expect(result.bodyHash).toBe(f.expectedBodyHash);
      expect(result.canonical).toBe(f.expectedCanonical);
      expect(result.signature).toBe(f.expectedSignature);
    });
  }
});

describe('signRequest — negative paths (parity should fail on tampering)', () => {
  it('different secret produces different signature', async () => {
    const f = vectors.fixtures[0]!;
    const result = await signRequest({
      apiKey: f.apiKey,
      hmacSecret: f.hmacSecret + 'x',
      method: f.method,
      path: f.canonicalPath,
      query: f.canonicalQuery,
      body: f.body,
      timestamp: f.timestamp,
    });
    expect(result.signature).not.toBe(f.expectedSignature);
  });

  it('modified body produces different signature', async () => {
    const f = vectors.fixtures[1]!;
    const result = await signRequest({
      apiKey: f.apiKey,
      hmacSecret: f.hmacSecret,
      method: f.method,
      path: f.canonicalPath,
      query: f.canonicalQuery,
      body: { ...f.body, extra_field: 'tamper' },
      timestamp: f.timestamp,
    });
    expect(result.signature).not.toBe(f.expectedSignature);
  });

  it('modified timestamp produces different signature', async () => {
    const f = vectors.fixtures[1]!;
    const result = await signRequest({
      apiKey: f.apiKey,
      hmacSecret: f.hmacSecret,
      method: f.method,
      path: f.canonicalPath,
      query: f.canonicalQuery,
      body: f.body,
      timestamp: f.timestamp + 1,
    });
    expect(result.signature).not.toBe(f.expectedSignature);
  });

  it('different method produces different signature', async () => {
    const f = vectors.fixtures[1]!;
    const result = await signRequest({
      apiKey: f.apiKey,
      hmacSecret: f.hmacSecret,
      method: 'GET',
      path: f.canonicalPath,
      query: f.canonicalQuery,
      body: f.body,
      timestamp: f.timestamp,
    });
    expect(result.signature).not.toBe(f.expectedSignature);
  });
});

describe('signRequest — default timestamp is current time', () => {
  it('uses Date.now() when timestamp is omitted', async () => {
    const before = Date.now();
    const result = await signRequest({
      apiKey: 'k',
      hmacSecret: 's',
      method: 'POST',
      path: '/functions/v1/test',
      query: '',
      body: {},
    });
    const after = Date.now();
    const ts = Number(result.timestamp);
    expect(ts).toBeGreaterThanOrEqual(before);
    expect(ts).toBeLessThanOrEqual(after);
  });
});
